"""empty message

Revision ID: 453841322852
Revises: 
Create Date: 2018-01-21 21:38:47.423980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453841322852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('owner', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'owner')
    # ### end Alembic commands ###
