"""empty message

Revision ID: 482606376e75
Revises: 99a2b458df87
Create Date: 2018-02-06 20:02:17.839000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482606376e75'
down_revision = '99a2b458df87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'event', 'user', ['owner'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    # ### end Alembic commands ###
