"""empty message

Revision ID: 99a2b458df87
Revises: 
Create Date: 2018-02-04 16:30:03.440000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a2b458df87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvp', sa.Column('event_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'rsvp_event_fkey', 'rsvp', type_='foreignkey')
    op.create_foreign_key(None, 'rsvp', 'event', ['event_id'], ['id'])
    op.drop_column('rsvp', 'event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvp', sa.Column('event', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rsvp', type_='foreignkey')
    op.create_foreign_key(u'rsvp_event_fkey', 'rsvp', 'event', ['event'], ['id'])
    op.drop_column('rsvp', 'event_id')
    # ### end Alembic commands ###
