"""empty message

Revision ID: bdd218f66bb0
Revises: 
Create Date: 2018-01-29 18:37:43.461000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd218f66bb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'event_eventname_key', 'event', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'event_eventname_key', 'event', ['eventname'])
    # ### end Alembic commands ###
